import competenceIcon from "./../assets/SVG/Competences-icon.svg";
import experienceIcon from "./../assets/SVG/experience-icon.svg";
import contactIcon from "./../assets/SVG/contact-icon.svg";
import HTMLIcon from "./../assets/SVG/HTML-icon.svg";
import CSSIcon from "./../assets/SVG/CSS-icon.svg";
import mongoDBIcon from "./../assets/SVG/MongoDB-icon.svg";
import tailwindsCSSIcon from "./../assets/SVG/Tailwindss-icon.svg";
import figmaIcon from "./../assets/SVG/Figma-icon.svg";
import photoshopIcon from "./../assets/SVG/Photoshop-icon.svg";
import nodejsIcon from "./../assets/SVG/NodeJS-icon.svg";
import javascriptIcon from "./../assets/SVG/Javacript-icon.svg";
import websiteIcon from "./../assets/SVG/Website-icon.svg";
import locationIcon from "./../assets/SVG/Location-icon.svg";
import projetIcon from "./../assets/SVG/projets-icon.svg";
import arrowIcon from "./../assets/SVG/Arrow-icon.svg";
import drawMobile from "./../assets/SVG/about-dra-mobile.svg"